apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  type: LoadBalancer  # This will expose the service externally
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: mlops

